#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
UI/UX Pro Max Export v2.0 - Export design systems as Tailwind config,
CSS variables, and Design Tokens (Style Dictionary format).
"""

import json
from pathlib import Path
from datetime import datetime


def _hex_to_rgb(hex_color: str) -> tuple:
    """Convert hex color to RGB tuple."""
    hex_color = hex_color.lstrip('#')
    if len(hex_color) == 3:
        hex_color = ''.join(c * 2 for c in hex_color)
    try:
        return tuple(int(hex_color[i:i+2], 16) for i in (0, 2, 4))
    except (ValueError, IndexError):
        return (0, 0, 0)


def _generate_dark_palette(colors: dict) -> dict:
    """Generate dark mode color variants from light palette."""
    dark = {}
    for role, hex_val in colors.items():
        if role in ("notes",):
            continue
        if not hex_val or not hex_val.startswith('#'):
            dark[role] = hex_val
            continue
        
        r, g, b = _hex_to_rgb(hex_val)
        
        if role == "background":
            # Dark background: very dark
            dark[role] = "#0F172A"
        elif role == "text":
            # Dark text: light
            dark[role] = "#F1F5F9"
        elif role in ("primary", "secondary", "cta"):
            # Lighten primary/secondary/cta for dark mode
            r = min(255, int(r * 1.2 + 30))
            g = min(255, int(g * 1.2 + 30))
            b = min(255, int(b * 1.2 + 30))
            dark[role] = f"#{r:02X}{g:02X}{b:02X}"
        else:
            dark[role] = hex_val
    
    return dark


def export_tailwind_config(design_system: dict, output_dir: str = None) -> str:
    """Generate tailwind.config.js from design system."""
    colors = design_system.get("colors", {})
    typography = design_system.get("typography", {})
    dark_colors = _generate_dark_palette(colors)
    
    heading_font = typography.get("heading", "Inter")
    body_font = typography.get("body", "Inter")
    
    config = f"""/** @type {{import('tailwindcss').Config}} */
// Generated by UI/UX Pro Max v2.0 — {datetime.now().strftime("%Y-%m-%d %H:%M")}
// Project: {design_system.get("project_name", "Untitled")}

module.exports = {{
  content: [
    "./src/**/*.{{js,ts,jsx,tsx,html,vue,svelte}}",
    "./app/**/*.{{js,ts,jsx,tsx}}",
    "./components/**/*.{{js,ts,jsx,tsx}}",
    "./pages/**/*.{{js,ts,jsx,tsx}}",
  ],
  darkMode: "class",
  theme: {{
    extend: {{
      colors: {{
        primary: {{
          DEFAULT: "{colors.get('primary', '#2563EB')}",
          dark: "{dark_colors.get('primary', '#60A5FA')}",
          50: "{_lighten(colors.get('primary', '#2563EB'), 0.95)}",
          100: "{_lighten(colors.get('primary', '#2563EB'), 0.9)}",
          200: "{_lighten(colors.get('primary', '#2563EB'), 0.75)}",
          300: "{_lighten(colors.get('primary', '#2563EB'), 0.6)}",
          400: "{_lighten(colors.get('primary', '#2563EB'), 0.4)}",
          500: "{colors.get('primary', '#2563EB')}",
          600: "{_darken(colors.get('primary', '#2563EB'), 0.15)}",
          700: "{_darken(colors.get('primary', '#2563EB'), 0.3)}",
          800: "{_darken(colors.get('primary', '#2563EB'), 0.45)}",
          900: "{_darken(colors.get('primary', '#2563EB'), 0.6)}",
        }},
        secondary: {{
          DEFAULT: "{colors.get('secondary', '#3B82F6')}",
          dark: "{dark_colors.get('secondary', '#93C5FD')}",
        }},
        cta: {{
          DEFAULT: "{colors.get('cta', '#F97316')}",
          dark: "{dark_colors.get('cta', '#FB923C')}",
          hover: "{_darken(colors.get('cta', '#F97316'), 0.1)}",
        }},
        background: {{
          DEFAULT: "{colors.get('background', '#F8FAFC')}",
          dark: "{dark_colors.get('background', '#0F172A')}",
        }},
        foreground: {{
          DEFAULT: "{colors.get('text', '#1E293B')}",
          dark: "{dark_colors.get('text', '#F1F5F9')}",
        }},
      }},
      fontFamily: {{
        heading: ["{heading_font}", "system-ui", "sans-serif"],
        body: ["{body_font}", "system-ui", "sans-serif"],
      }},
      spacing: {{
        "xs": "4px",
        "sm": "8px",
        "md": "16px",
        "lg": "24px",
        "xl": "32px",
        "2xl": "48px",
        "3xl": "64px",
      }},
      borderRadius: {{
        "sm": "4px",
        "md": "8px",
        "lg": "12px",
        "xl": "16px",
        "2xl": "24px",
      }},
      boxShadow: {{
        "sm": "0 1px 2px rgba(0,0,0,0.05)",
        "md": "0 4px 6px rgba(0,0,0,0.1)",
        "lg": "0 10px 15px rgba(0,0,0,0.1)",
        "xl": "0 20px 25px rgba(0,0,0,0.15)",
      }},
      transitionDuration: {{
        "fast": "150ms",
        "normal": "200ms",
        "slow": "300ms",
      }},
    }},
  }},
  plugins: [],
}};
"""
    
    if output_dir:
        output_path = Path(output_dir) / "tailwind.config.js"
        output_path.parent.mkdir(parents=True, exist_ok=True)
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(config)
        return f"Exported: {output_path}"
    
    return config


def export_css_variables(design_system: dict, output_dir: str = None) -> str:
    """Generate CSS custom properties file from design system."""
    colors = design_system.get("colors", {})
    typography = design_system.get("typography", {})
    dark_colors = _generate_dark_palette(colors)
    
    heading_font = typography.get("heading", "Inter")
    body_font = typography.get("body", "Inter")
    google_url = typography.get("google_fonts_url", "")
    css_import = typography.get("css_import", "")
    
    css = f"""/* UI/UX Pro Max v2.0 — Design System Variables */
/* Project: {design_system.get("project_name", "Untitled")} */
/* Generated: {datetime.now().strftime("%Y-%m-%d %H:%M")} */

"""
    
    if css_import:
        css += f"{css_import}\n\n"
    elif google_url:
        css += f"/* Google Fonts: {google_url} */\n\n"
    
    css += f""":root {{
  /* Colors — Light Mode */
  --color-primary: {colors.get('primary', '#2563EB')};
  --color-secondary: {colors.get('secondary', '#3B82F6')};
  --color-cta: {colors.get('cta', '#F97316')};
  --color-background: {colors.get('background', '#F8FAFC')};
  --color-text: {colors.get('text', '#1E293B')};
  --color-cta-hover: {_darken(colors.get('cta', '#F97316'), 0.1)};
  --color-primary-light: {_lighten(colors.get('primary', '#2563EB'), 0.9)};
  --color-border: #E2E8F0;
  --color-muted: #94A3B8;

  /* Typography */
  --font-heading: "{heading_font}", system-ui, sans-serif;
  --font-body: "{body_font}", system-ui, sans-serif;
  --font-size-xs: 0.75rem;
  --font-size-sm: 0.875rem;
  --font-size-base: 1rem;
  --font-size-lg: 1.125rem;
  --font-size-xl: 1.25rem;
  --font-size-2xl: 1.5rem;
  --font-size-3xl: 1.875rem;
  --font-size-4xl: 2.25rem;
  --font-size-5xl: 3rem;
  --line-height-tight: 1.25;
  --line-height-normal: 1.5;
  --line-height-relaxed: 1.75;

  /* Spacing */
  --space-xs: 0.25rem;
  --space-sm: 0.5rem;
  --space-md: 1rem;
  --space-lg: 1.5rem;
  --space-xl: 2rem;
  --space-2xl: 3rem;
  --space-3xl: 4rem;

  /* Shadows */
  --shadow-sm: 0 1px 2px rgba(0,0,0,0.05);
  --shadow-md: 0 4px 6px rgba(0,0,0,0.1);
  --shadow-lg: 0 10px 15px rgba(0,0,0,0.1);
  --shadow-xl: 0 20px 25px rgba(0,0,0,0.15);

  /* Border Radius */
  --radius-sm: 4px;
  --radius-md: 8px;
  --radius-lg: 12px;
  --radius-xl: 16px;
  --radius-full: 9999px;

  /* Transitions */
  --transition-fast: 150ms ease;
  --transition-normal: 200ms ease;
  --transition-slow: 300ms ease;

  /* Z-Index Scale */
  --z-dropdown: 10;
  --z-sticky: 20;
  --z-fixed: 30;
  --z-modal-backdrop: 40;
  --z-modal: 50;
  --z-popover: 60;
  --z-tooltip: 70;
}}

/* Dark Mode */
[data-theme="dark"],
.dark {{
  --color-primary: {dark_colors.get('primary', '#60A5FA')};
  --color-secondary: {dark_colors.get('secondary', '#93C5FD')};
  --color-cta: {dark_colors.get('cta', '#FB923C')};
  --color-background: {dark_colors.get('background', '#0F172A')};
  --color-text: {dark_colors.get('text', '#F1F5F9')};
  --color-cta-hover: {_lighten(dark_colors.get('cta', '#FB923C'), 0.15)};
  --color-primary-light: {_darken(dark_colors.get('primary', '#60A5FA'), 0.7)};
  --color-border: #334155;
  --color-muted: #64748B;
}}

@media (prefers-color-scheme: dark) {{
  :root:not([data-theme="light"]) {{
    --color-primary: {dark_colors.get('primary', '#60A5FA')};
    --color-secondary: {dark_colors.get('secondary', '#93C5FD')};
    --color-cta: {dark_colors.get('cta', '#FB923C')};
    --color-background: {dark_colors.get('background', '#0F172A')};
    --color-text: {dark_colors.get('text', '#F1F5F9')};
    --color-border: #334155;
    --color-muted: #64748B;
  }}
}}

/* Utility Classes */
.text-primary {{ color: var(--color-primary); }}
.text-secondary {{ color: var(--color-secondary); }}
.text-cta {{ color: var(--color-cta); }}
.bg-primary {{ background-color: var(--color-primary); }}
.bg-secondary {{ background-color: var(--color-secondary); }}
.bg-cta {{ background-color: var(--color-cta); }}

/* Reduced Motion */
@media (prefers-reduced-motion: reduce) {{
  *,
  *::before,
  *::after {{
    animation-duration: 0.01ms !important;
    animation-iteration-count: 1 !important;
    transition-duration: 0.01ms !important;
    scroll-behavior: auto !important;
  }}
}}
"""
    
    if output_dir:
        output_path = Path(output_dir) / "design-system.css"
        output_path.parent.mkdir(parents=True, exist_ok=True)
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(css)
        return f"Exported: {output_path}"
    
    return css


def export_design_tokens(design_system: dict, output_dir: str = None) -> str:
    """Generate Design Tokens in Style Dictionary format."""
    colors = design_system.get("colors", {})
    typography = design_system.get("typography", {})
    dark_colors = _generate_dark_palette(colors)
    
    tokens = {
        "$metadata": {
            "generator": "UI/UX Pro Max v2.0",
            "project": design_system.get("project_name", "Untitled"),
            "generated": datetime.now().isoformat(),
            "category": design_system.get("category", "General"),
            "style": design_system.get("style", {}).get("name", "")
        },
        "color": {
            "light": {
                "primary": {"value": colors.get("primary", "#2563EB"), "type": "color"},
                "secondary": {"value": colors.get("secondary", "#3B82F6"), "type": "color"},
                "cta": {"value": colors.get("cta", "#F97316"), "type": "color"},
                "background": {"value": colors.get("background", "#F8FAFC"), "type": "color"},
                "text": {"value": colors.get("text", "#1E293B"), "type": "color"},
                "border": {"value": "#E2E8F0", "type": "color"},
                "muted": {"value": "#94A3B8", "type": "color"},
                "primary-50": {"value": _lighten(colors.get("primary", "#2563EB"), 0.95), "type": "color"},
                "primary-100": {"value": _lighten(colors.get("primary", "#2563EB"), 0.9), "type": "color"},
                "primary-200": {"value": _lighten(colors.get("primary", "#2563EB"), 0.75), "type": "color"},
                "primary-300": {"value": _lighten(colors.get("primary", "#2563EB"), 0.6), "type": "color"},
                "primary-400": {"value": _lighten(colors.get("primary", "#2563EB"), 0.4), "type": "color"},
                "primary-500": {"value": colors.get("primary", "#2563EB"), "type": "color"},
                "primary-600": {"value": _darken(colors.get("primary", "#2563EB"), 0.15), "type": "color"},
                "primary-700": {"value": _darken(colors.get("primary", "#2563EB"), 0.3), "type": "color"},
                "primary-800": {"value": _darken(colors.get("primary", "#2563EB"), 0.45), "type": "color"},
                "primary-900": {"value": _darken(colors.get("primary", "#2563EB"), 0.6), "type": "color"},
            },
            "dark": {
                "primary": {"value": dark_colors.get("primary", "#60A5FA"), "type": "color"},
                "secondary": {"value": dark_colors.get("secondary", "#93C5FD"), "type": "color"},
                "cta": {"value": dark_colors.get("cta", "#FB923C"), "type": "color"},
                "background": {"value": dark_colors.get("background", "#0F172A"), "type": "color"},
                "text": {"value": dark_colors.get("text", "#F1F5F9"), "type": "color"},
                "border": {"value": "#334155", "type": "color"},
                "muted": {"value": "#64748B", "type": "color"},
            }
        },
        "typography": {
            "fontFamily": {
                "heading": {"value": typography.get("heading", "Inter"), "type": "fontFamily"},
                "body": {"value": typography.get("body", "Inter"), "type": "fontFamily"},
            },
            "fontSize": {
                "xs": {"value": "0.75rem", "type": "fontSize"},
                "sm": {"value": "0.875rem", "type": "fontSize"},
                "base": {"value": "1rem", "type": "fontSize"},
                "lg": {"value": "1.125rem", "type": "fontSize"},
                "xl": {"value": "1.25rem", "type": "fontSize"},
                "2xl": {"value": "1.5rem", "type": "fontSize"},
                "3xl": {"value": "1.875rem", "type": "fontSize"},
                "4xl": {"value": "2.25rem", "type": "fontSize"},
                "5xl": {"value": "3rem", "type": "fontSize"},
            },
            "lineHeight": {
                "tight": {"value": "1.25", "type": "lineHeight"},
                "normal": {"value": "1.5", "type": "lineHeight"},
                "relaxed": {"value": "1.75", "type": "lineHeight"},
            }
        },
        "spacing": {
            "xs": {"value": "0.25rem", "type": "spacing"},
            "sm": {"value": "0.5rem", "type": "spacing"},
            "md": {"value": "1rem", "type": "spacing"},
            "lg": {"value": "1.5rem", "type": "spacing"},
            "xl": {"value": "2rem", "type": "spacing"},
            "2xl": {"value": "3rem", "type": "spacing"},
            "3xl": {"value": "4rem", "type": "spacing"},
        },
        "shadow": {
            "sm": {"value": "0 1px 2px rgba(0,0,0,0.05)", "type": "boxShadow"},
            "md": {"value": "0 4px 6px rgba(0,0,0,0.1)", "type": "boxShadow"},
            "lg": {"value": "0 10px 15px rgba(0,0,0,0.1)", "type": "boxShadow"},
            "xl": {"value": "0 20px 25px rgba(0,0,0,0.15)", "type": "boxShadow"},
        },
        "borderRadius": {
            "sm": {"value": "4px", "type": "borderRadius"},
            "md": {"value": "8px", "type": "borderRadius"},
            "lg": {"value": "12px", "type": "borderRadius"},
            "xl": {"value": "16px", "type": "borderRadius"},
            "full": {"value": "9999px", "type": "borderRadius"},
        },
        "transition": {
            "fast": {"value": "150ms ease", "type": "transition"},
            "normal": {"value": "200ms ease", "type": "transition"},
            "slow": {"value": "300ms ease", "type": "transition"},
        }
    }
    
    output = json.dumps(tokens, indent=2, ensure_ascii=False)
    
    if output_dir:
        output_path = Path(output_dir) / "design-tokens.json"
        output_path.parent.mkdir(parents=True, exist_ok=True)
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(output)
        return f"Exported: {output_path}"
    
    return output


def export_design_system(query: str, project_name: str = None, 
                         export_format: str = "all", output_dir: str = None) -> str:
    """Main export entry point."""
    from design_system import DesignSystemGenerator
    
    generator = DesignSystemGenerator()
    design_system = generator.generate(query, project_name)
    
    results = []
    out_dir = output_dir or "."
    
    if export_format in ("tailwind", "all"):
        result = export_tailwind_config(design_system, out_dir)
        results.append(f"Tailwind: {result}")
    
    if export_format in ("css", "all"):
        result = export_css_variables(design_system, out_dir)
        results.append(f"CSS: {result}")
    
    if export_format in ("tokens", "all"):
        result = export_design_tokens(design_system, out_dir)
        results.append(f"Tokens: {result}")
    
    return "\n".join(results)


# ============ COLOR UTILITIES ============
def _lighten(hex_color: str, amount: float) -> str:
    """Lighten a hex color by mixing with white."""
    if not hex_color or not hex_color.startswith('#'):
        return "#FFFFFF"
    r, g, b = _hex_to_rgb(hex_color)
    r = int(r + (255 - r) * amount)
    g = int(g + (255 - g) * amount)
    b = int(b + (255 - b) * amount)
    return f"#{min(255,r):02X}{min(255,g):02X}{min(255,b):02X}"


def _darken(hex_color: str, amount: float) -> str:
    """Darken a hex color by mixing with black."""
    if not hex_color or not hex_color.startswith('#'):
        return "#000000"
    r, g, b = _hex_to_rgb(hex_color)
    r = int(r * (1 - amount))
    g = int(g * (1 - amount))
    b = int(b * (1 - amount))
    return f"#{max(0,r):02X}{max(0,g):02X}{max(0,b):02X}"
